### ISSUE TITLE
Syntax error on "New Ticket"

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#187]
@jeff - As administrator, in staff panel, when clicking on "New ticket", I get this message :
Parse error: syntax error, unexpected end of file in /var/www/html/ost/include/staff/ticket-open.inc.php on line 312
(I'm on linux)

**Comment by soif** [comment]
can't reproduce this in 1.7-rc1/develop (I'm on linux too)..

**Comment by drewx0r** [comment]
@protich This is caused by the use of PHP short tags used in staff/ticket-open.inc.php (and client/faq.inc.php). See posts #23 and #24 in this thread: http://osticket.com/forums/showthread.php?t=8077

To fix the issue until RC2 comes out, you can either

a) enable short tags in your php.ini file

or 

b) change instances of `<?=` to `<?php` (note the trailing space). There is also one instance of 

`<?
            } ?>`

where `php` should be added after the `<?` (there is one of these in faq.inc.php as well).

**Comment by protich** [comment]
@drewx0r - Fix coming - it also includes `staff/ticket-edit.inc.php` and `staff/cannedreply.inc.php`

**Comment by greezybacon** [comment]
This was fixed and a lint test was added to find short tags in the future. Thanks for reporting
