### ISSUE TITLE
How to Add Extra Fields 

### ISSUE THREAD

**Issue by veilex** [osTicket/osTicket-1.7#48]
I like to be able to add extra field to input store number in Client Side tickect site, staff site

my email is tech@veilex.com

**Comment by protich** [comment]
Dynamic fields won't be supported in 1.7. It's on our todo list for future version.

**Comment by greezybacon** [comment]
I think we should track the future-version feature-maybes here, unless there's another list I don't know about -- which is entirely possible

**Comment by greezybacon** [comment]
Veilex,

Could you post an exact specification for what you're looking for and include an example? I want to make sure everybody understands the feature as you see it. 

Do bear in mind that you're welcome to take a stab at implementing it and send a pull request.

**Comment by protich** [comment]
Jared - My feeling is not to get feature request in Github. We have a forum for that. Github should be limited to bug/code related issues, otherwise it will turn out to be a forum. That is my 2 cents.

**Comment by veilex** [comment]
Mr. Greezybacon

Thank you for your response. The only thing I need is to have a field where the store number of my client shows up. For example, when you create a ticket they will be able to click on a tab and select the store number.

**Comment by mikhey54** [comment]
+1

**Comment by greezybacon** [comment]
Veilex,

Are you talking about a text box to enter and track the store number with, or are you talking about a drop-down list to select the store number from?

**Comment by veilex** [comment]
Mr. Greezybacon Yes I'm  talking about a drop-down list to select the store number from?

**Comment by veilex** [comment]
Mr. Greezybacon  If you tell me what I need to do, copy,edit ,del move,  I will do it but i need someone to tell me answer or instruction

**Comment by veilex** [comment]
Mr. Greezybacon Yes I'm talking about a drop-down list to select the store number from

**Comment by veilex** [comment]
Do i get any repond on this

**Comment by greezybacon** [comment]
Let's get something straight, Veilex: I don't work for you. If this is indeed something for which you need commercial attention, osTicket has official, [commercial support](http://www.osticket.com/support/index.php) services available.

That said, osTicket has a future feature planned for dynamic forms that will allow administrators to create various forms associated to help topics that will assist in tracking other information along with the tickets -- customer store number included. Your request jogged an interesting twist we intend to support with the idea of pre-administered drop-down selection lists for the forms, which will be a great addition to the feature.

Unfortunately, since this is a big feature to implement and makes significant changes to the UI, it won't make the cut for 1.7. Furthermore, the general osTicket community has no use specifically for a "store number" drop-down, so it doesn't make sense to implement it in the public version exactly as you describe it either.

If you wish to implement it as a mod on the installs you administer, you will need to add a table to store the store numbers, a column to the ost_ticket table to store the store number associated with the ticket, mod the class.ticket.php script to support the new field, add the HTML field to the include/client/open.inc.php to add the field to the open-ticket form, add support in class.ticket.php:Ticket::create to validate and transfer the field value to the database.

It you want to keep going, you can add a column to the staff tickets patch in include/staff/tickets.inc.php perhaps with sort and export capabilities. You might also want to add support to include/staff/ticket-edit.php so that a staff member could edit the store-number after the fact. If you want staff members to be able to set the store-number when they create tickets, you'll need to add the drop-down list in include/staff/ticket-open.inc.php.

You can still keep going -- mod the ticket search form to also search for store-number, perhaps adding it to the advanced search form. You might want to link SLAs to the store number or handle store numbers in the email filtering feature. And, since you can create tickets through the API now, you might want to  add support for the store number there too.

I hope I'm painting the picture well that this isn't a small feature, and the core developers want to make sure that the feature, when implemented, will be broad enough to be useful for most every osTicket install, considering it touches so many facets of the project.

Cheers and happy coding
