### ISSUE TITLE
Require cryptographic extension to enable mail integration.

### ISSUE THREAD

**Issue by protich** [osTicket/osTicket-1.7#627]
osTicket was recently featured in a [bad cryptography showcase](http://www.cryptofails.com/2013/07/osticket-fail-open-fail-often.html).  While the author, in my opinion, fails to make the important distinction between user's passwords and mail server credentials  - the post nonetheless raised an important point. 
## 

**Background**
To connect to the mail server (SMTP/POP/IMAP) a password in plain text is required. osTicket relies on mcrypt php extension to encrypt and decrypt mail server password on the fly but **it's not a requirement**. A warning message is usually logged _every time_ a password is stored in plain text. 

The rationale was to allow users in shared hosting accounts who cannot possibly install extensions to use osTicket's mail integration as long as they're aware of the risks of storing passwords in plain text.

**_Staff's passwords are always hashed - never encrypted_.**
## 

**Proposed Solution**
- Starting with 1.7.1 (upcoming release) - osTicket will require one of the cryptographic extensions to enabled mail integration.
- Support other cryptographic extensions... e.g openssl
- Use better encryption key/salt
- Improve default salt for old installations

**Comment by defuse** [comment]
(I am the author of that blog post). I must apologize for not sending you guys a note about the post, I just forgot to do it. That was bad disclosure practice on my part, and I am sorry.

Thanks for the clarification - I will correct the post.

Here's a proper implementation of mcrypt encryption in PHP, which you can use or take as an example: https://defuse.ca/secure-php-encryption.htm (scroll down past the big red warning). Something like the SecureRandom() function in that code should be used to generate the key instead of microtime(), which provides very little entropy.

**Comment by protich** [comment]
@defuse - Thank you for the feedback and clarification. The issues raised are valid and will be addressed.

**Comment by greezybacon** [comment]
This was addressed by providing a pure-PHP encryption library so that passwords can always be encrypted

**Comment by greezybacon** [comment]
Released with v1.7.1
