### ISSUE TITLE
Persistent session not working? a possible solution

### ISSUE THREAD

**Issue by sabas** [osTicket/osTicket-1.7#653]
Every time I accessed the admin panel (/scp/), I had to relogin again, so here it is a possible solution

I found that moving line 38 in main.inc.php
   //ini_set('session.cookie_path','/osticket/');
to line 74 after 
   define('SQL_DIR', UPGRADE_DIR.'sql/');

and rewriting it as 
ini_set('session.cookie_path',ROOT_PATH);

recovers the session and no more login panel every time.

I don't send a pull request because I don't know why that line was commented..

**Comment by greezybacon** [comment]
Thanks for identifying this. We've actually had a considerable amount of trouble out of the bug. I have mocked up the issue as follows:

``` php
$is_https = (isset($_SERVER['HTTPS'])
        && strtolower($_SERVER['HTTPS']) == 'on')
    || (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
        && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) == 'https');

session_set_cookie_params(86400, dirname($_SERVER['PHP_SELF']),
    $_SERVER['HTTP_HOST'], $is_https);
```

Could you retest with something like the above code?

**Comment by greezybacon** [comment]
What browser did you observe this in by chance?

**Comment by sabas** [comment]
Latest Chrome!
I'll test tomorrow morning, because I have the installation in the pc I'm using at work.. That one is a xampp distribution on windows xp (now I'm on linux, I can try also here)

Edit: as a matter of fact, chrome on linux I don't notice the bug.. :/ The patch (put on line 38) caused not to login with error "session time out due to inactivity"

**Comment by sabas** [comment]
With the solution https://github.com/osTicket/osTicket-1.7/issues/653#issuecomment-21962384 I couldn't login ("Authentication required"). The pull request same (btw the code from that branch seems different from the develop branch' 1.).
I also tried to delete and reinstall (I'm using 1.7 stable + the bootstrap theme from the forums)

**Comment by greezybacon** [comment]
@sabas, did you test with the branch I posted in #655?

> (btw the code from that branch seems different from the develop branch' 1.).

I'm not following quite you mean

**Comment by sabas** [comment]
@greezybacon yep I tried that, sorry I badly wrote the message..
I tried both patching following #655 pull request and reinstalling directly that branch. I didn't see cookies also (don't know if it's an useful info, but the way I tried produces in Chrome a PHPSESSID cookie with the correct folder)

**Comment by greezybacon** [comment]
Honestly, I don't see what's different between the suggestions. 

``` php
ini_set('session.cookie_path', ROOT_PATH)
```

will set the `session.cookie_path` to `./` since `ROOT_PATH` is statically defined as `./` in the `develop` branch. The code in the pull-request branch actually correctly detects `ROOT_PATH` now, if you have osTicket served from a directory (other than /).

``` php
session_set_cookie_params(86400, ROOT_PATH, $_SERVER['HTTP_HOST'],
        osTicket::is_https());
```

will set `session.cookie_path` to the correct `ROOT_PATH` -- `/osticket/` for instance if you host osTicket at `http://my.domain.com/osticket`.

I'm not seeing why setting the `cookie_path` to `./` works and the real `ROOT_PATH` wouldn't. Do you have a case-sensitive issue going on? Perhaps your browser is requesting `/osTicket/` and the cookie path set in php is `/osticket/` or something squirly?

**PS** _I'm not trying to say that your incorrect, I'm just very annoyed by this issue and really want to understand what's causing it and how to correctly fix it_

**Comment by sabas** [comment]
My osticket url is
http://localhost/company/intranet/support/ so no case sensitivity, and I'm accessing it via localhost, not via anotheer ip..
Additionally, the intranet app writes cookies and a session (I used this project to handle authentication https://github.com/bencrowder/alibaba ), perhaps conflicts?

Can be Windows messing up with paths?

PS I know how you feel :-)

**Comment by greezybacon** [comment]
@sabas, would you mind testing again with the pull-request branch?

This is what I think is happening: you have another PHP application that is hosted on the same server, perhaps out of a parent folder like `/company` or `/company/intranet`. It is issuing a cookie named PHPSESSID for the same domain (`localhost` in this case) for a path that is a parent of `/company/intranet/support/`, or perhaps not specifying a path at all and assuming `/`.

What I've observed with PHP/osTicket is that, if the browser has a PHPSESSID cookie for the domain or parent domain of osTicket, it will go ahead and send the cookie to osTicket. PHP will accept the cookie and start a new session using the same session-id. When the login process completes and the user is authenticated, osTicket will generate a new session-id and send a new Set-Cookie header to the client. Now the client has two possibly-valid cookies. So, when it makes the next request to the tickets.php page (or whatever was given in the 302/redirect response from the login process), both PHPSESSID cookies are sent from the browser in the request:

```
Cookie: PHPSESSID=2d2d51v06dm6gukgmbgk5s32l; PHPSESSID=a1sq7dm89kltffa2gd5uf242g
```

For some reason it seems that the browser will send the new cookie (`a1sq...`) second, but PHP will use the first cookie as the session-id. Since the session under `2d2d..` in this case does not have a valid login token, the login page is served again.

This process will continue (with the `2d2d...` cookie and each of the new cookies issued by PHP) as long and as many times as you want to authenticate. If you were to close your browser or clear the cookie cache and visit the osTicket page first, it should work correctly. The problem is the existing PHPSESSID cookie for the same domain and compatible path.

The last fix I applied was to change the name of the session-id cookie for osTicket, to `OSTSESSID`. This should prevent it from clobbering other PHP applications using PHPSESSID.

**Comment by sabas** [comment]
Installed and on scp I had

```
Fatal error: Call to a member function getSessionName() on a non-object in /opt/lampp/htdocs/osTicket/include/class.ostsession.php on line 44
```

Testing with isset gives opens the login page but at login dies with

```
Valid CSRF Token Required
```

**Comment by greezybacon** [comment]
My bad. It's a dependency issue. Could you try just replacing `$cfg->getSessionName()` with `'OSTSESSID'`?

**Comment by sabas** [comment]
It requires the csrf token (dies with that error message), I don't see where's created...

**Comment by greezybacon** [comment]
It shouldn't trigger that error. I'm sorry I wasn't able to test the code before I posted it. I'll test it next week.

**Comment by sabas** [comment]
@greezybacon I get
Valid CSRF Token Required

I uploaded directly the files overwriting previous ones.

**Comment by greezybacon** [comment]
@sabas, I guess we're talking about two completely different issues. The CSRF engine is cookie based, but I didn't make any changes to the processing of CSRF tokens. They're generated in class.osticket.php and class.csrf.php

**Comment by sabas** [comment]
So I don't know how it's originated, cause it happened after update.. :/ If you can give some advice, I'll try to reproduce the error and open another issue :-)
