### ISSUE TITLE
"implement template for password reset"

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket-1.7#666]
Hi guys, first of all thank you for your work. It's great!

I just want to report what I received : an alert email after having clicked on the template edition  (upgrade from osticket 1.7.0 to fresh 1.7.1) : 

[DELETE FROM ost_config WHERE `namespace`="pwreset"
            AND `value`=1]

Unknown column 'namespace' in 'where clause'

Regards.

**Comment by greezybacon** [comment]
@jeffchulg, thanks for reporting the issue. 

What I think happened, is that you upgraded from the stock 1.7.0 to the 1.7.1-rc1. The config table was refactored along the way between the two versions. And, when you log in (ie. _before_ you upgraded), the system attempts to remove any password reset tokens for your account. Then, because the database needed to be migrated, you got the error.

Things should be stable after you completed the upgrade, since the config table was migrated to the new format.

**Comment by greezybacon** [comment]
Fixed in #696, thanks again for reporting it
