### ISSUE TITLE
Ability to show/hide department column in tickets view

### ISSUE THREAD

**Issue by OleSta** [osTicket/osTicket-1.7#747]
I would like this to be part of the official releases:
https://github.com/henesnarfel/osTicket-1.7/commit/993ca5a6a6b48cae3503a98ede221fbf9113ed9e

**Comment by protich** [comment]
I kindly disagree - see #485 for background discussion.

**Comment by OleSta** [comment]
I don't understand if it is the showing of the department column in the open ticket view you don't like or the option for the user to enable/disable the column.
I would just like an admin option to enable showing department for assigned/unassigned open and answered tickets.

**Comment by protich** [comment]
You can show department now by hiding assigned tickets on open queue. See Admin Panel > Settings > Tickets.

Adding the option is a hack which doesn't solve the real issue. You might want to show department but someone else might want due date - would it call for yet another admin option to choose the column to show? See my comment on PR #485.

**Comment by sphen13** [comment]
i see from your comment what you suggest and while it does work for a "staff" user it does not for an "admin" - when logged in as an admin user it always shows the assigned person.  i will experiment and see if i can accomplish what i need with a regular staff user (or more like a manager) but not sure if this is expected behavior.
