### ISSUE TITLE
Cannot add collaborators

### ISSUE THREAD

**Issue by rocklee44** [osTicket/osTicket-1.7#926]
Hi all,
My environment : Centos 8 , osTicket Version v1.17 , Apache/2.4.37 , PHP 8.0.24 , MySQL 8.0.26
My account has administrator permission , this is screenshot when I try to add collaborators to ticket:
![11](https://user-images.githubusercontent.com/12525493/204436294-2be669e6-6a25-4d54-83d3-b30169b0dc02.PNG)
This is php error log:
```
[29-Nov-2022 03:55:03 UTC] PHP Fatal error:  Uncaught Error: Object of class StaffLDAPAuthentication could not be converted to string in /opt/www/osTicket-v1.17/upload/include/class.auth.php:422
Stack trace:
#0 /opt/www/osTicket-v1.17/upload/include/class.auth.php(422): array_unique()
#1 /opt/www/osTicket-v1.17/upload/include/class.auth.php(427): AuthenticationBackend::getSearchDirectories()
#2 /opt/www/osTicket-v1.17/upload/include/ajax.users.php(47): AuthenticationBackend::searchUsers()
#3 /opt/www/osTicket-v1.17/upload/include/class.dispatcher.php(151): UsersAjaxAPI->search()
#4 /opt/www/osTicket-v1.17/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch()
#5 /opt/www/osTicket-v1.17/upload/include/class.dispatcher.php(120): Dispatcher->resolve()
#6 /opt/www/osTicket-v1.17/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch()
#7 /opt/www/osTicket-v1.17/upload/scp/ajax.php(326): Dispatcher->resolve()
#8 {main}
  thrown in /opt/www/osTicket-v1.17/upload/include/class.auth.php on line 422
```
I have LDAP Authentication and Lookup 0.6.2 connect to 2 Active Directory servers (2 forests) successfully.
![12](https://user-images.githubusercontent.com/12525493/204436899-fb21435b-313f-405a-bf02-c4e24eb589e1.PNG)
Please give me some advice, thank you very much.

**Comment by JediKev** [comment]
@rocklee44 

Please use [our Forum](https://forum.osticket.com) next time. However, since you already opened this I will provide an answer:

Please upgrade to v1.17.2, install the latest build of the LDAP plugin, and retest. v1.17 had quite a few bugs that were subsequently addressed in later versions.

If you continue to run into issues please search through our Forum for existing threads. If you don’t see one make one yourself and provide clear details as you have here.

**Note:**
If you upgraded from a previous version and didn’t install the latest build of the LDAP plugin before upgrading then there are further things you will need to do which are outlined in some of the Forum posts.

Cheers.
