### ISSUE TITLE
Space before some email headers make email not readable

### ISSUE THREAD

**Issue by ByCzech** [osTicket/osTicket-1.7#928]
Email from osTicket are sent in Mime Format. But arive in plain text with base64 coded blocks, so user can't read it. This is because some email headers has space before it. When i manualy delete this space, then email is pefrectly decoded by email client.

Headers with space on their begin:

Message-ID, Return-Path, X-Mailer, From, Mime-Version, Content-Type.

**Comment by JediKev** [comment]
@ByCzech 

This is the wrong repo. You should open Issues [here instead](https://github.com/osTicket/osTicket).

With this being said, once you open one there you need to provide a screenshot of Admin Panel > Dashboard > Information. You are likely using an older version of osTicket which is why you are seeing such issues.

Cheers.
